# Generated by Django 3.1.5 on 2021-01-21 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=999)),
                ('history', models.TextField(max_length=999)),
                ('sexual_orientation', models.CharField(max_length=30)),
                ('breed', models.CharField(choices=[('Whites', 'Whites'), ('Dun', 'Dun'), ('Black', 'Black'), ('Yellow', 'Yellow'), ('Native', 'Native')], max_length=30)),
                ('ethnicity', models.CharField(choices=[('Whites', 'Whites'), ('Black', 'Black'), ('Native', 'Native'), ('Dun', 'Dun'), ('Mulatto', 'Mulatto'), ('Caboclos', 'Caboclos'), ('Cafuzos', 'Cafuzos')], max_length=30)),
                ('school_level', models.CharField(choices=[('Complete primary education', 'Complete primary education'), ('Incomplete elementary school', 'Incomplete elementary school'), ('Complete high school', 'Complete high school'), ('Incomplete high school', 'Incomplete high school'), ('Complete higher education', 'Complete higher education'), ('Incomplete higher education', 'Incomplete higher education'), ('Higher education more', 'Higher education more')], max_length=40)),
            ],
            options={
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('DF', 'Distrito Federal')], max_length=2)),
            ],
            options={
                'db_table': 'nationality',
            },
        ),
        migrations.CreateModel(
            name='Homeless',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=13, verbose_name='RG')),
                ('issuing_body', models.CharField(blank=True, max_length=12)),
                ('height', models.DecimalField(decimal_places=3, max_digits=8)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=8)),
                ('blood_type', models.CharField(choices=[('A +', 'A +'), ('A -', 'A -'), ('AB +', 'AB +'), ('AB -', 'AB -'), ('O +', 'O +'), ('O -', 'O -')], max_length=4)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('about', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='register.about')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.nationality')),
            ],
            options={
                'db_table': 'homeless',
            },
        ),
    ]
