# Generated by Django 3.1.5 on 2021-01-19 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeless',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=13, verbose_name='RG')),
                ('issuing_body', models.CharField(blank=True, max_length=12)),
                ('height', models.DecimalField(decimal_places=4, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('blood_type', models.CharField(choices=[('A +', 'A +'), ('A -', 'A -'), ('AB +', 'AB +'), ('AB -', 'AB -'), ('O +', 'O +'), ('O -', 'O -')], max_length=4)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('about', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.about')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.nationality')),
            ],
            options={
                'db_table': 'homeless',
            },
        ),
    ]
