# Generated by Django 3.1.5 on 2021-01-21 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_homeless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeless',
            name='about',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='register.about'),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.nationality'),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
