# Generated by Django 3.1.5 on 2021-01-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210121_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeless',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
