# Generated by Django 3.1.5 on 2021-01-31 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20210131_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeless',
            old_name='user',
            new_name='use',
        ),
    ]
