# Generated by Django 3.1.5 on 2021-01-31 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20210131_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeless',
            old_name='use',
            new_name='user',
        ),
    ]
