# Generated by Django 3.1.5 on 2021-01-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20210131_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeless',
            name='frist_name',
            field=models.CharField(max_length=30, verbose_name='frist_name'),
        ),
    ]
