# Generated by Django 3.1.5 on 2021-02-06 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20210131_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addiction',
            name='homeless',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.homeless', verbose_name='Sem-teto'),
        ),
        migrations.AlterField(
            model_name='addiction',
            name='name_addiction',
            field=models.CharField(max_length=200, verbose_name='Nome do vício'),
        ),
        migrations.AlterField(
            model_name='addiction',
            name='type_addiction',
            field=models.CharField(max_length=200, verbose_name='Tipo do vício'),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='about',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='register.about', verbose_name='História/Sobre'),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='birth_date',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='blood_type',
            field=models.CharField(choices=[('A +', 'A +'), ('A -', 'A -'), ('AB +', 'AB +'), ('AB -', 'AB -'), ('O +', 'O +'), ('O -', 'O -')], max_length=4, verbose_name='Tipo sanguíneo'),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='frist_name',
            field=models.CharField(max_length=30, verbose_name='Primeiro nome'),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='height',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='issuing_body',
            field=models.CharField(blank=True, max_length=12, verbose_name='Órgão expedidor'),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.nationality', verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='nickname',
            field=models.CharField(max_length=30, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='second_name',
            field=models.CharField(max_length=30, verbose_name='Segundo nome'),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Peso'),
        ),
    ]
