# Generated by Django 3.1.5 on 2021-02-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20210206_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='breed',
            field=models.CharField(choices=[('Brancos', 'Brancos'), ('Pardos', 'Pardos'), ('Pretos', 'Pretos'), ('Indígenas', 'Indígenas'), ('Amarelos', 'Amarelos')], max_length=30, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='about',
            name='ethnicity',
            field=models.CharField(choices=[('Brancos', 'Brancos'), ('Pretos', 'Pretos'), ('Indígenas', 'Indígenas'), ('Pardos', 'Pardos'), ('Mulatos', 'Mulatos'), ('Caboclos', 'Caboclos'), ('Confusos', 'Confusos')], max_length=30, verbose_name='Etnia'),
        ),
        migrations.AlterField(
            model_name='about',
            name='school_level',
            field=models.CharField(choices=[('Analfabeto', 'Analfabeto'), ('Até 5º Ano Incompleto', 'Até 5º Ano Incompleto'), ('5º Ano Completo', '5º Ano Completo'), ('6º ao 9º Ano do Fundamental', '6º ao 9º Ano do Fundamental'), ('Fundamental Completo', 'Fundamental Completo'), ('Médio Incompleto', 'Médio Incompleto'), ('Médio Completo', 'Médio Completo'), ('Superior Incompleto', 'Superior Incompleto'), ('Superior Completo', 'Superior Completo'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Ignorado', 'Ignorado')], max_length=40, verbose_name='Níveis de escolaridade'),
        ),
    ]
