# Generated by Django 3.1.5 on 2021-02-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20210206_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=999, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='about',
            name='history',
            field=models.CharField(max_length=999, verbose_name='História'),
        ),
    ]
